INSERT INTO CREADOR (ID_CREADOR,NOMBRE) VALUES ('1','Marvel');
SELECT * FROM CREADOR;
SELECT * FROM PERSONAJES;
INSERT INTO CREADOR (ID_CREADOR,NOMBRE) VALUES ('2','DC Comics');
INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('1','Bruce Banner',
'Hulk','160','600 mil','75','98','1962','Físico Nuclear','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('2','Tony Stark',
'Iron Man','170','200 mil','70','123','1963','Inventor Industrial','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('3','Thor Odinson',
'Thor','145','infinita','100','235','1962','Rey de Asgard','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('4','Wnda Maximoff',
'Bruja Escarlata','170','100 mil','90','345','1964','Bruja','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('5','Carol Danvers',
'Capitana Marvel','157','250 mil','85','128','1968','Oficial de Inteligencia','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('6','Thanos',
'Thanos','170','infinita','40','306','1976','Adorador de la Muerte','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('7','Peter Parker',
'Spiderman','165','25 mil','80','74','1962','Fotógrafo','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('8','Steve Rogers',
'Capitan America','145','600','45','60','1941','Oficial Federal','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('9','Bobby Drake',
'Ice Man','140','2 mil','64','122','1963','Contador','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('10','Barry Allen',
'Flash','160','10 mil','120','168','1956','Científico Forense','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('11','Bruce Wayne',
'Batman','170','500','32','47','1939','Hombre de Negocios','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('12','Clark Kent',
'Superman','165','infinita','120','182','1948','Reportero','1') ;

INSERT INTO PERSONAJES (ID_PERSONAJE,NOMBRE_REAL,PERSONAJE,INTELIGENCIA,
FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('13','Diana Prince',
'Mujer Maravilla','160','infinita','95','127','1949','Princesa Guerrera','1') ;

UPDATE PERSONAJES SET APARICION = '1938' WHERE ID_PERSONAJE = 12;

DELETE FROM PERSONAJES WHERE ID_PERSONAJE = 10;

DROP SCHEMA SUPERHEROES;
