SELECT * FROM EMPLEADOS;
SELECT * FROM DEPARTAMENTOS;
SELECT NOMBRE_DEPTO FROM DEPARTAMENTOS;
SELECT NOMBRE, SAL_EMP FROM EMPLEADOS;
SELECT COMISION_EMP FROM EMPLEADOS;
SELECT * FROM EMPLEADOS WHERE CARGO_EMP = 'Secretaria';
SELECT * FROM EMPLEADOS WHERE CARGO_EMP = 'Vendedor' ORDER BY NOMBRE ASC;
SELECT NOMBRE, CARGO_EMP FROM EMPLEADOS ORDER BY SAL_EMP DESC; 
SELECT NOMBRE AS 'Nombre', CARGO_EMP AS 'Cargo' FROM EMPLEADOS ;
SELECT SAL_EMP,COMISION_EMP FROM EMPLEADOS WHERE ID_DEPTO = 2000 ORDER BY COMISION_EMP DESC;
SELECT NOMBRE, SAL_EMP, (SAL_EMP + COMISION_EMP + 500) FROM EMPLEADOS WHERE ID_DEPTO=3000 ORDER BY NOMBRE;
SELECT NOMBRE FROM EMPLEADOS WHERE NOMBRE LIKE 'J%';
SELECT NOMBRE, SAL_EMP, COMISION_EMP, (SAL_EMP + COMISION_EMP) AS SALARIO_TOTAL FROM EMPLEADOS WHERE COMISION_EMP > 1000;
SELECT NOMBRE, SAL_EMP AS SALARIO_TOTAL FROM EMPLEADOS WHERE COMISION_EMP = 0;
SELECT * FROM EMPLEADOS WHERE COMISION_EMP > SAL_EMP;
SELECT * FROM EMPLEADOS WHERE (COMISION_EMP<=(SAL_EMP*0.3));
SELECT * FROM EMPLEADOS WHERE NOMBRE NOT LIKE '%MA%';
SELECT * FROM DEPARTAMENTOS WHERE (NOMBRE_DEPTO = 'VENTAS' OR NOMBRE_DEPTO = 'INVESTIGACIÓN' OR NOMBRE_DEPTO = 'MANTENIMIENTO');
SELECT * FROM DEPARTAMENTOS WHERE (NOMBRE_DEPTO <> 'VENTAS' AND NOMBRE_DEPTO <> 'INVESTIGACIÓN' AND NOMBRE_DEPTO <> 'MANTENIMIENTO');
SELECT MAX(SAL_EMP) FROM EMPLEADOS ;
SELECT MAX(NOMBRE) FROM EMPLEADOS;
SELECT MAX(SAL_EMP) AS MAS_ALTO, MIN(SAL_EMP) AS MAS_BAJO, (MAX(SAL_EMP)-MIN(SAL_EMP)) AS DIFERENCIA FROM EMPLEADOS;
SELECT AVG(SAL_EMP) FROM EMPLEADOS;
SELECT AVG(SAL_EMP) FROM EMPLEADOS;
	
SELECT D.NOMBRE_DEPTO, COUNT(*) FROM DEPARTAMENTOS D, EMPLEADOS E
 WHERE D.ID_DEPTO = E.ID_DEPTO
 GROUP BY D.NOMBRE_DEPTO
 HAVING COUNT(*)>3;
 select * from empleados;
SELECT COD_JEFE, NOMBRE, COUNT(ID_EMP) AS CANTIDAD_DE_EMPLEADOS  
 FROM EMPLEADOS 
 GROUP BY COD_JEFE
 HAVING COUNT(ID_EMP)>=2;
 SELECT D.NOMBRE_DEPTO, COUNT(*)
 FROM DEPARTAMENTOS D, EMPLEADOS E 
 WHERE D.ID_DEPTO=E.ID_DEPTO
 GROUP BY D.NOMBRE_DEPTO
 HAVING COUNT(*)=0;
 SELECT * FROM EMPLEADOS WHERE SAL_EMP > ( SELECT AVG(SAL_EMP) FROM EMPLEADOS);
 