SELECT NOMBRE FROM PRODUCTO;
SELECT NOMBRE, PRECIO FROM PRODUCTO;
SELECT * FROM PRODUCTO;
SELECT NOMBRE, ROUND(PRECIO) FROM PRODUCTO;
SELECT CODIGO_FABRICANTE FROM producto;
SELECT CODIGO_FABRICANTE FROM producto GROUP BY codigo_fabricante;
SELECT NOMBRE FROM FABRICANTE ORDER BY NOMBRE;
SELECT NOMBRE, PRECIO FROM PRODUCTO ORDER BY NOMBRE ASC, PRECIO DESC;
SELECT * FROM FABRICANTE limit 5;
SELECT NOMBRE, PRECIO FROM PRODUCTO
ORDER BY PRECIO LIMIT 1;
SELECT NOMBRE, PRECIO FROM PRODUCTO
ORDER BY PRECIO DESC LIMIT 1;
SELECT NOMBRE FROM PRODUCTO WHERE PRECIO=120;
SELECT * FROM PRODUCTO WHERE PRECIO between 60 AND 200;
SELECT * FROM PRODUCTO WHERE CODIGO IN (1,3,5);
SELECT NOMBRE FROM PRODUCTO WHERE NOMBRE LIKE '%Portátil%';
SELECT P.CODIGO,P.NOMBRE,F.CODIGO,F.NOMBRE FROM FABRICANTE F INNER JOIN PRODUCTO P;
SELECT P.NOMBRE,P.PRECIO,F.NOMBRE FROM FABRICANTE F INNER JOIN PRODUCTO P ORDER BY P.NOMBRE;
SELECT P.NOMBRE, P.PRECIO,F.NOMBRE FROM PRODUCTO P INNER JOIN FABRICANTE F ORDER BY P.PRECIO LIMIT 1;
SELECT * FROM PRODUCTO P INNER JOIN FABRICANTE F  WHERE F.NOMBRE LIKE 'Lenovo';
SELECT * FROM PRODUCTO P INNER JOIN FABRICANTE F  WHERE F.NOMBRE LIKE 'Crucial' AND P.PRECIO>200;
SELECT * FROM PRODUCTO P INNER JOIN FABRICANTE F WHERE F.NOMBRE IN ('Asus','Hewlett-Packard');
SELECT P.NOMBRE, P.PRECIO, F.NOMBRE FROM PRODUCTO P INNER JOIN FABRICANTE F WHERE P.PRECIO>=180 ORDER BY P.PRECIO ASC, P.NOMBRE DESC;
SELECT * FROM FABRICANTE;
SELECT * FROM PRODUCTO;
SELECT F.NOMBRE, P.NOMBRE, P.PRECIO FROM FABRICANTE F LEFT JOIN PRODUCTO P ON P.CODIGO_FABRICANTE = F.CODIGO;
SELECT * FROM FABRICANTE F LEFT JOIN PRODUCTO P ON P.CODIGO_FABRICANTE = F.CODIGO WHERE NOT F.CODIGO = ANY (SELECT CODIGO_FABRICANTE FROM PRODUCTO);
SELECT * FROM PRODUCTO WHERE CODIGO_FABRICANTE = (SELECT CODIGO FROM FABRICANTE WHERE NOMBRE='Lenovo');
SELECT * FROM PRODUCTO WHERE PRECIO = (SELECT MAX(PRECIO) FROM PRODUCTO WHERE CODIGO_FABRICANTE = (SELECT CODIGO FROM FABRICANTE WHERE NOMBRE = 'Lenovo'));
SELECT NOMBRE FROM PRODUCTO WHERE PRECIO = (SELECT MAX(PRECIO) FROM PRODUCTO WHERE CODIGO_FABRICANTE = (SELECT CODIGO FROM FABRICANTE WHERE NOMBRE = 'Lenovo'));
SELECT * FROM PRODUCTO WHERE CODIGO_FABRICANTE = (SELECT CODIGO FROM FABRICANTE WHERE NOMBRE = 'Asus') AND PRECIO > (SELECT AVG(PRECIO) FROM PRODUCTO WHERE CODIGO_FABRICANTE = (SELECT CODIGO FROM FABRICANTE WHERE NOMBRE = 'Asus'));
/* Subconsultas con IN y NOT IN*/
SELECT f.nombre FROM fabricante f inner join producto p where p.codigo_fabricante in (select codigo from fabricante) group by nombre;
SELECT f.nombre FROM fabricante f inner join producto p where f.codigo not in (select codigo_fabricante from producto) group by nombre;
/*	Subconsultas (En la cláusula HAVING)	*/
SELECT f.NOMBRE, count(P.codigo_fabricante) FROM FABRICANTE f inner join producto p
where f.codigo=p.codigo_fabricante and p.codigo_fabricante <> (SELECT CODIGO FROM FABRICANTE WHERE NOMBRE LIKE 'Lenovo')
group by P.codigo_fabricante
HAVING count(P.codigo_fabricante) = (SELECT COUNT(*) FROM PRODUCTO WHERE codigo_fabricante = 
(SELECT CODIGO FROM FABRICANTE WHERE NOMBRE LIKE 'Lenovo'));