SELECT nombre FROM jugadores order by NOMBRE ASC;
SELECT NOMBRE FROM JUGADORES WHERE POSICION LIKE 'C' AND PESO > 200;
SELECT NOMBRE FROM EQUIPOS ORDER BY NOMBRE ASC;
SELECT NOMBRE FROM EQUIPOS WHERE conferencia LIKE 'EAST';
SELECT * FROM EQUIPOS WHERE CIUDAD LIKE 'C%';
SELECT NOMBRE, NOMBRE_EQUIPO FROM JUGADORES ORDER BY NOMBRE_EQUIPO ASC;
SELECT * FROM JUGADORES WHERE NOMBRE_EQUIPO LIKE 'RAPTORS';
SELECT E.PUNTOS_POR_PARTIDO FROM ESTADISTICAS E INNER JOIN JUGADORES J WHERE E.JUGADOR=J.CODIGO AND J.NOMBRE LIKE 'PAU GASOL';
SELECT E.PUNTOS_POR_PARTIDO FROM ESTADISTICAS E INNER JOIN JUGADORES J 
WHERE E.JUGADOR=J.CODIGO AND J.NOMBRE LIKE 'PAU GASOL' AND TEMPORADA LIKE '04/05';
SELECT SUM(E.PUNTOS_POR_PARTIDO),J.NOMBRE FROM ESTADISTICAS E INNER JOIN JUGADORES J where E.JUGADOR = J.CODIGO GROUP BY J.NOMBRE;
SELECT COUNT(J.NOMBRE), E.NOMBRE FROM JUGADORES J INNER JOIN EQUIPOS E WHERE J.NOMBRE_EQUIPO = E.NOMBRE group by E.NOMBRE;
SELECT SUM(E.PUNTOS_POR_PARTIDO),J.NOMBRE FROM ESTADISTICAS E INNER JOIN JUGADORES J where E.JUGADOR = J.CODIGO GROUP BY J.NOMBRE order by E.PUNTOS_POR_PARTIDO desc limit 1;
select codigo, equipo_local, equipo_visitante, case when p.puntos_local>p.puntos_visitante then equipo_local
            when p.puntos_local<p.puntos_visitante then equipo_visitante 
            else null end as equipo_ganador
from partidos p;

